# netlify.toml - CREATE THIS FILE IN PROJECT ROOT
[build]
  publish = "build"
  functions = "functions"

[dev]
  publish = "build"
  functions = "functions"
  targetPort = 3000
  port = 8888

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200